production:
  host: 'localhost'
  adapter: 'postgresql'
  encoding: utf-8
  database: 'passdb'
  username: 'postgres'
  password: 'passdb_pass'

development:
  adapter: 'sqlite3'
  database: 'db/passdb.sqlite3'
