production:
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  adapter: 'postgresql'
  encoding: utf-8

development:
  adapter: 'sqlite3'
  database: 'db/passdb.sqlite3'
